### ISSUE TITLE
Enhance Data for Deployments

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-backend#88]
**Is your feature request related to a problem? Please describe.**
I need to be able to sort the deployments by date/time, and would like more contextual data I can work with.

**Describe the solution you'd like**
I would like to see more information for a deployment, like this:

- `running` currently is a boolean, so if we check on the frontend for this as a status, it means we can only show the user that the deployment is either "running" or "stopped", but if it's failed it will just show as "stopped"
- `date/time` to be able to sort by date/time
- `errors` maybe an array of errors or warnings?
- Any other information people might want to know about a deployment, like `cluster` and `namespace`, maybe `version`, or even `number of steps` could be interesting? I doubt we could show _who_ deployed it, like the `user` but in the future that'd be nice.

**Comment by Delawen** [comment]
`datetime` can be returned.

`namespace` is kind of dummy to return right now because it is included as a parameter on the query to return the list of deployments. But we can add it, just in case we extend it to support multiple namespaces.

Problematic data:

`errors` is kind of problematic because it means reading from the log of the camel-k operator (or whatever operator we use if we move beyond camel) and check what is happening. I will return an empty array for now, but not sure how to fill this. Even for a human reading the camel-k operator log it is sometimes not clear where is the error and to what deployment it refers to.

For the same reason, `running` may be difficult to map to something that is not a "Running" or "Stopped". Each type of CustomResource have a different set of statuses. The boolean simplifies the whole list. If we allow more statuses... what would they be? Do we mimic KameletBindings?

`version` is a concept we don't have right now. To return it we need first to define what `version` means for us.

`cluster` is also weird because clusters don't have a name. What should I return then? 

`number of steps` is also an advanced feature that probably requires a bit more definition once we enter the EIP world. I can parse each CRD and try to get the number of steps, but is it not a bit overkill for just the list of deployments?

`user` that deployed it is something we also don't have.
